# Generated by Django 4.2.5 on 2023-10-03 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='item_id',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.CharField(max_length=1000),
        ),
    ]
