# Generated by Django 4.2.5 on 2023-10-03 18:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_alter_cartitem_item_id_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='item_id',
            new_name='product_id',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product_image_url',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='added_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
