# Generated by Django 4.2.5 on 2023-10-05 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_favoriteitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='product_title',
            field=models.CharField(default='', max_length=500),
        ),
    ]
