# Generated by Django 4.2.5 on 2023-10-05 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0017_cartitem_product_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoriteitem',
            name='product_title',
            field=models.CharField(default='', max_length=500),
        ),
    ]
