# Generated by Django 4.2.5 on 2023-10-05 14:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0018_favoriteitem_product_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='country',
            field=models.CharField(choices=[('INDIA', 'India'), ('USA', 'United States'), ('CAN', 'Canada')], default='INDIA', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.localtime, editable=False),
        ),
    ]
