# Generated by Django 4.2.5 on 2023-10-06 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0021_remove_product_image_url_remove_product_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='productId',
        ),
    ]
