# Generated by Django 4.2.5 on 2023-10-06 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0022_remove_product_productid'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productNumber',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
