# Generated by Django 4.2.5 on 2023-10-06 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0023_product_productnumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='product',
            new_name='productNumber',
        ),
        migrations.AlterField(
            model_name='product',
            name='productNumber',
            field=models.CharField(default='', max_length=255),
        ),
    ]
