# Generated by Django 4.2.5 on 2023-10-07 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0026_alter_cartitem_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='productNumber',
        ),
    ]
