# Generated by Django 4.2.5 on 2023-10-10 05:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0027_remove_product_productnumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('total_price', models.PositiveIntegerField(default=1)),
                ('ordered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='services.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='ordered_items',
            field=models.ManyToManyField(blank=True, related_name='users_order', through='services.OrderItem', to='services.product'),
        ),
    ]
