# Generated by Django 4.2.5 on 2023-10-12 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0028_orderitem_customuser_ordered_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='ordered_items',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
