# Generated by Django 4.1.5 on 2023-09-16 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_login_delete_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='Password',
            field=models.IntegerField(),
        ),
    ]
