# Generated by Django 4.1.5 on 2023-09-16 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_login_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
