# Generated by Django 5.0.1 on 2024-02-01 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0004_alter_user_options_remove_user_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
