# Generated by Django 5.0.1 on 2024-01-27 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_usertype_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('seller', 'Seller')], default='user', max_length=20),
        ),
        migrations.DeleteModel(
            name='UserType',
        ),
    ]
